spring:
  application:
    name: api-veiculos
  datasource:
    url: jdbc:postgresql://localhost:5432/veiculosdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /docs

jwt:
  secret: ZGV2ZWxvcGltZW50ZGV2ZWxvcGltZW50ZGV2ZWxvcGltZW50MTIzNDU2
  expiration: 86400000
